## ML - Assignment 9 - BAM (Bidirectional Associative Memory)
### Done by: **Milan Ashvinbhai Bhuva (IIT2018176)**
-----

### **Problem Statement**

Given

- **Set A**:  
    - X1 = [1 1 1 1 1 1 ]
    - X2 = [-1 -1 -1 -1 -1 -1 ]
    - X3 = [1 -1 -1 1 1 1 ]
    - X4 = [1 1 -1 -1 -1 -1 ]
<br><br>

- **Set B**:  
    - Y1 = [1 1 1]
    - Y2 = [-1 -1 -1]
    - Y3 = [-1 1 1]
    - Y4 = [1 -1 1]


- Using BAM algorithm, train a W matrix for BAM which can retrieve all the above mentioned 4 pairs. 
- Hence test the level of weight corrections of the BAM with examples.
----

### **Import modules**

In [1]:
import numpy as np
import random
import math

-----

### **Representing given data**

- Given the X components, I club them into a single vector ```using np.array()```.
- The same thing is done for Y matrices.
- This is done so that the calculation of the weight matrix is efficient and easy.

In [2]:
X1 = [1, 1, 1, 1, 1, 1]
X2 = [-1, -1, -1, -1, -1, -1]
X3 = [1, -1, -1, 1, 1, 1]
X4 = [1, 1, -1, -1, -1, -1]

X = np.array([X1, X2, X3, X4])

Y1 = [1, 1, 1]
Y2 = [-1, -1, -1]
Y3 = [-1, 1, 1]
Y4 = [1, -1, 1]

Y = np.array([Y1, Y2, Y3, Y4])

print("X = ", X)
print("\nY = ", Y)
print("\n\nDimensions of X: ", X.shape)
print("\nDimensions of Y: ", Y.shape)

X =  [[ 1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1]
 [ 1 -1 -1  1  1  1]
 [ 1  1 -1 -1 -1 -1]]

Y =  [[ 1  1  1]
 [-1 -1 -1]
 [-1  1  1]
 [ 1 -1  1]]


Dimensions of X:  (4, 6)

Dimensions of Y:  (4, 3)


----

### **BAM implementation diagram**

![image](https://user-images.githubusercontent.com/55105941/97803508-fd352c00-1c6f-11eb-8538-b3ba2d9a1ddd.png)

----

### **Weight Matrix**

- The weight matrix can be calculated using:
    - **Vectorisation**: In this method, the weight matrix is obtained by calculating the dot product between X and Y vectors calculated above.

In [3]:
def calcWeight(X, Y):
    return np.dot(X.T, Y)

weight = calcWeight(X, Y)
print('W = ', weight, end = "")

print("\n\nDimensions of Weight Matrix: ",weight.shape)

W =  [[2 2 4]
 [4 0 2]
 [2 2 0]
 [0 4 2]
 [0 4 2]
 [0 4 2]]

Dimensions of Weight Matrix:  (6, 3)


----

### **Testing**

- In testing, the goal is to verify if our weight matrix is correct.
- In **forward testing**, the Y matrices will be multiplied with the weights to **obtain corresponding X matrices**.
- In **backward testing**, the X matrices will be multiplied with the weights to **obtain corresponding Y matrices**.
- I will be using the bipolar activation function, which will categorize the **values <= 0 as -1 and values > 0 as 1**.
- Below is a representation of the bipolar activation function.

![bipolar](https://user-images.githubusercontent.com/55105941/97907639-939a4800-1d6b-11eb-8870-2b04e2c3d6ab.png)

#### **Why is bipolar activation function used?**

- This is because, considering the given sets A and B, the **value domain consists of 1 and -1**.
- Hence, this is the only activation function where f(x) = {-1, 1} for any x.

In [4]:
def ForwardBipolarActivation(matrix, weight):
    matrix[matrix > 0] = 1
    matrix[matrix <= 0] = -1
    return np.array(matrix)

def BackwardBipolarActivation(matrix, weight):
    matrix[matrix >= 0] = 1
    matrix[matrix < 0] = -1
    return np.array(matrix)

----
### **Forward Testing**

- We perform the following operation on all the Y (set B) matrices and verify if our result matches with the corresponding set A (X) matrices. 

    $
        Y(i) * weight^T = X_i
    $
----

In [5]:
def forward(Y, weight): 
  x = np.dot(Y, weight.T) 
  return ForwardBipolarActivation(x, weight)

In [6]:
print("\nweight * Y1 = ", forward(Y1, weight), " = X1")
print("\nweight * Y2 = ", forward(Y2, weight), " = X2")
print("\nweight * Y3 = ", forward(Y3, weight), " = X3")
print("\nweight * Y4 = ", forward(Y4, weight), " = X4")

print("\n\nIt is observed that the obtained results match with the original X matrices.\n\nThus forward testing is 100% accurate.")


weight * Y1 =  [1 1 1 1 1 1]  = X1

weight * Y2 =  [-1 -1 -1 -1 -1 -1]  = X2

weight * Y3 =  [ 1 -1 -1  1  1  1]  = X3

weight * Y4 =  [ 1  1 -1 -1 -1 -1]  = X4


It is observed that the obtained results match with the original X matrices.

Thus forward testing is 100% accurate.


----
### **Backward Testing**
- We perform the following operation on all the X (set A) matrices and verify if our result matches with the corresponding set B (Y) matrices. 

    $
        weight^T * X_i = Y_i
    $
----

In [7]:
def backward(X, weight): 
  Y = np.dot(weight.T, X) 
  return BackwardBipolarActivation(Y, weight)

In [8]:
print("\nweight * X1 = ", backward(X1, weight), " = Y1")
print("\nweight * X2 = ", backward(X2, weight), " = Y2")
print("\nweight * X3 = ", backward(X3, weight), " = Y3")
print("\nweight * X4 = ", backward(X4, weight), " = Y4")

print("\n\nIt is observed that the obtained results match with the original Y (target) matrices.\n\nThus backward testing is 100% accurate.")


weight * X1 =  [1 1 1]  = Y1

weight * X2 =  [-1 -1 -1]  = Y2

weight * X3 =  [-1  1  1]  = Y3

weight * X4 =  [ 1 -1  1]  = Y4


It is observed that the obtained results match with the original Y (target) matrices.

Thus backward testing is 100% accurate.


-----